name: CI

on:
  push:
    branches: [ "master", "ci-test"]
  pull_request:
    branches: [ "master" ]

jobs:
  guix-build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Guix
      run: sudo apt-get install -y guix
    - uses: actions/checkout@v3
    - name: guix build
      run: guix time-machine -c$(nproc) -M 8 -- build -f guix.scm -c$(nproc) -M 8