name: CI

on:
  push:
    branches: [ "master", "ci-test"]
  pull_request:
    branches: [ "master" ]

jobs:
  guix-build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Guix
      run: sudo apt-get install -y guix
    - name: update Guix
      run: guix pull
    - name: restart Guix
      run: sudo systemctl restart guix-daemon.service
    - uses: actions/checkout@v3
    - name: guix build
      run: guix build -f guix.scm